### ISSUE TITLE
MariaDB: Nullable number fields with a default of null are incorrectly handled

### ISSUE THREAD

**Issue by far-blue** [atlasphp/Atlas.Info#10]
The patch for MariaDB that handles the 'NULL' string for nullable fields with null default works great for strings but because the patch is in the mysql child class's extractColumn() method the parent (Info) class's version of extractDefault() will already have been run and clobbered the null default on number field types.

This means that nullable int, float, double and real types with a null default in mariadb (which report the default as 'NULL') will have their default set to 0 or 0.0 instead.

**Comment by far-blue** [comment]
I've submitted a PR (#11) to fix this issue.

**Comment by pmjones** [comment]
Fixed by #11
