### ISSUE TITLE
Any chance of a new release

### ISSUE THREAD

**Issue by far-blue** [atlasphp/Atlas.Info#14]
Hi all,

There's been a few commits to the 1.x branch since the last release - including 2 accepted PRs from me. Any chance of rolling a new release?

**Comment by pmjones** [comment]
Oh goodness yes of course -- look for it later today!

**Comment by pmjones** [comment]
Sorry gentlemen, won't be able to finish until tomorrow. Thank you for your patience.

**Comment by pmjones** [comment]
My apologies for the continued delay, running into trouble with the release process.

**Comment by pmjones** [comment]
1.2.1 has been released (finally). Thank you for your patience!

**Comment by far-blue** [comment]
most appreciated, thank you :)
