### ISSUE TITLE
MariaDB default empty string results in a default of ''

### ISSUE THREAD

**Issue by far-blue** [atlasphp/Atlas.Info#8]
I'm specifying MariaDB tables with `DEFAULT ''` for fields and I'm seeing, as a result, Row and Table classes generated by Skeleton are being created with default values of `'\'\''`. This in turn means the default content of a string field isn't an empty string but, instead, the string `''`.

Am I missing something or setting up a default empty string on my fields incorrectly or is this a bug? I'm pretty sure it didn't used to happen because when I ran skeleton on an older project recently it decided it wanted to update 125 existing classes. I'm thinking it might be a MariaDB change of behaviour?

**Comment by far-blue** [comment]
I've created a PR for a suggested fix for this - PR #9 

I also note that the fix for `'NULL'` for mariadb from 2019 still hasn't been released - it would be great if this PR and the previous NULL fix could be wrapped into a new release :)

**Comment by pmjones** [comment]
Fixed by #9
